# Generated by Django 4.0.1 on 2022-01-22 11:25

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Краткий сюжет')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=profiles.models.movie_images_upload)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.movie')),
            ],
            options={
                'verbose_name': 'Изображение к фильму',
                'verbose_name_plural': 'Изображения к фильму',
            },
        ),
    ]
