# Generated by Django 4.0.1 on 2022-03-02 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
